// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2CBufwC7OdVGLRDTqWagU5dCmyqR-p3A',
    appId: '1:746014102635:android:9cf7c84dda68b8e49c8d2e',
    messagingSenderId: '746014102635',
    projectId: 'narailcity-3b9f5',
    storageBucket: 'narailcity-3b9f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAJZES3NLea9cFQKqj6qySHsy1Y258qBY',
    appId: '1:746014102635:ios:8b237473abc91d789c8d2e',
    messagingSenderId: '746014102635',
    projectId: 'narailcity-3b9f5',
    storageBucket: 'narailcity-3b9f5.firebasestorage.app',
    iosBundleId: 'com.example.narailCity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAJZES3NLea9cFQKqj6qySHsy1Y258qBY',
    appId: '1:746014102635:ios:8b237473abc91d789c8d2e',
    messagingSenderId: '746014102635',
    projectId: 'narailcity-3b9f5',
    storageBucket: 'narailcity-3b9f5.firebasestorage.app',
    iosBundleId: 'com.example.narailCity',
  );
}
